name: Parity check

on:
  push:
  pull_request:

jobs:
  parity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (CPU only)
        run: |
          python -m pip install --upgrade pip
          pip install --index-url https://download.pytorch.org/whl/cpu torch
          pip install numpy "jax[cpu]" dm-haiku
          pip install git+https://github.com/google-deepmind/tracr.git

      - name: Compile & export tracr
        run: python scripts/compile_export.py

      - name: Verify parity (fail if mismatch)
        run: python scripts/parity_check.py
